server:
  port: 7002
spring:
  application:
    name: spring_websocket
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_learning?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    #Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
  #Thymeleaf
  servlet:
    multipart:
      max-file-size: 1MB


#mybatis配置
mybatis-plus:
  mapper-locations: classpath:com/kk/learning/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0
  type-aliases-package: com.kk.learning.entity
